"""add users and device_ownership tables

Revision ID: ac994f8fce7b
Revises: 
Create Date: 2026-08-31 12:04:12.759590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac994f8fce7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_ownership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('bound_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id')
    )
    op.create_index(op.f('ix_device_ownership_device_id'), 'device_ownership', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_ownership_user_id'), 'device_ownership', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', name='devicestatus'), nullable=False),
    sa.Column('last_seen_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('fall_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_imu_json', sa.JSON(), nullable=False),
    sa.Column('status_enum', sa.Enum('detected', 'acknowledged', name='fallstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fall_events_device_id'), 'fall_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_fall_events_timestamp_utc'), 'fall_events', ['timestamp_utc'], unique=False)
    op.create_table('haptic_commands_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('triggered_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_by_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_haptic_commands_log_device_id'), 'haptic_commands_log', ['device_id'], unique=False)
    op.create_table('processed_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msg_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.Enum('admin', 'clinician', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('processed_messages')
    op.drop_index(op.f('ix_haptic_commands_log_device_id'), table_name='haptic_commands_log')
    op.drop_table('haptic_commands_log')
    op.drop_index(op.f('ix_fall_events_timestamp_utc'), table_name='fall_events')
    op.drop_index(op.f('ix_fall_events_device_id'), table_name='fall_events')
    op.drop_table('fall_events')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_ownership_user_id'), table_name='device_ownership')
    op.drop_index(op.f('ix_device_ownership_device_id'), table_name='device_ownership')
    op.drop_table('device_ownership')
    # ### end Alembic commands ###
